language: go

go:
  - 1.11.x

services:
  - docker

before_deploy:
  - go test

after_success:
  - docker --version
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --region us-east-1)
  - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 410355896954.dkr.ecr.eu-west-1.amazonaws.com
  - docker build -t todo-app-api .
  - docker tag todo-app-api:latest 410355896954.dkr.ecr.eu-west-1.amazonaws.com/todo-app-api:latest
  - docker push 410355896954.dkr.ecr.eu-west-1.amazonaws.com/todo-app-api:latest